# Create a server based application and set homepage url and authorized redirect uris to the redirect uri
# and copy the client id and secret below

zoho:
  client_id: CLIENT_ID
  client_secret: CLIENT_SECRET
redirect_uri: "https://example.com" #do not change
